
development:
  adapter: postgresql
  encoding: utf8
  database: finish_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: finish_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: finish_production
  pool: 5
  username: postgres
  password: postgres
